#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.
cd src/

jars=`for i in ../../lib/*.jar; do echo -n "$i:"; done`
echo "Running DbAddCommit"
scala -classpath $jars. commiter.DbAddCommit $1 $2 "/home/verknowsys/JAVA/ScalaBot/codadris.scalaBot/"
