#!/bin/bash

date=`date "+%Y-%m-%d"`

mvn -e install:install-file -DcreateChecksum=true -Ddescription="Neodatis ODB, build on $date" -Dfile="lib/neodatis.jar" -DgeneratePom=true -DgroupId="org.neodatis" -DartifactId="neodatis-odb" -Dversion="1.9.17.632" -Dpackaging=jar