#!/bin/bash

date=`date "+%Y-%m-%d"`

mvn -e install:install-file -Ddescription="Quaqua swing-layout, build on $date" -Dfile="lib/quaqua-swing-layout.jar" -DgeneratePom=true -DgroupId="org.quaqua.swing-layout" -DartifactId="org.quaqua.swing-layout" -Dversion="5.4.1" -Dpackaging=jar