#!/bin/bash

date=`date "+%Y-%m-%d"`

mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi, build on $date" -Dfile="lib/qtjambi-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4" -Dversion="4.5.2" -Dpackaging=jar
mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi-MacOSX32, build on $date" -Dfile="lib/qtjambi-macosx-gcc-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4.lib.macosx32" -Dversion="4.5.2" -Dpackaging=jar
mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi-Linux32, build on $date" -Dfile="lib/qtjambi-linux32-gcc-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4.lib.linux32" -Dversion="4.5.2" -Dpackaging=jar
mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi-Linux64, build on $date" -Dfile="lib/qtjambi-linux64-gcc-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4.lib.linux64" -Dversion="4.5.2" -Dpackaging=jar
mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi-Windows32, build on $date" -Dfile="lib/qtjambi-win32-msvc2005-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4.lib.windows32" -Dversion="4.5.2" -Dpackaging=jar
mvn -e install:install-file -DcreateChecksum=true -Ddescription="Qt4-Jambi-Windows64, build on $date" -Dfile="lib/qtjambi-win64-msvc2005x64-4.5.2_01.jar" -DgeneratePom=true -DgroupId="com.qt4" -DartifactId="com.qt4.lib.windows64" -Dversion="4.5.2" -Dpackaging=jar