#!/bin/bash

date=`date "+%Y-%m-%d"`

mvn -e install:install-file -Ddescription="Quaqua, build on $date" -Dfile="lib/quaqua.jar" -DgeneratePom=true -DgroupId="org.quaqua" -DartifactId="org.quaqua" -Dversion="5.4.1" -Dpackaging=jar