#!/usr/bin/env ruby

libs = Dir["svd.utils/lib_managed/scala_2.8.1/compile/*.jar"]
libs << "svd.utils/target/scala_2.8.1/classes"
libs << "svd.cli/target/scala_2.8.1/classes"
libs << "svd.api/target/scala_2.8.1/classes"
libs << "svd.conf/target/scala_2.8.1/resources"
libs << "project/boot/scala-2.8.1/lib/scala-library.jar"

system("sudo rm -r logs")
system("sudo sbt 'project SvdCLI' compile") &&
system("java -cp " + libs.join(":") + " com.verknowsys.served.cli.Runner localhost 5555")
