#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

set -x
. OPTS

cd src/
mvn compile -o -Dmaven.test.skip.exec=true $@
mvn test -o $*
