#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

main="deployer.Deployer"
YOUR_CONFIG_FILENAME="project.tools.xml"

echo "Running $main"
java -classpath \
$HOME/.m2/repository/org/scala-lang/scala-compiler/2.7.5/scala-compiler-2.7.5.jar:\
$HOME/.m2/repository/org/scala-lang/scala-library/2.7.5/scala-library-2.7.5.jar:\
$HOME/.m2/repository/junit/junit/4.5/junit-4.5.jar:\
$HOME/.m2/repository/sshtools/j2ssh-common/0.2.2/j2ssh-common-0.2.2.jar:\
$HOME/.m2/repository/sshtools/j2ssh-core/0.2.2/j2ssh-core-0.2.2.jar:\
$HOME/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar:\
$HOME/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:\
$HOME/.m2/repository/log4j/log4j/1.2.14/log4j-1.2.14.jar:\
$HOME/.m2/repository/org/scala-lang/scala-library/2.7.5/scala-library-2.7.5.jar:\
$HOME/.m2/repository/org/neodatis/odb/neodatis-odb/1.9-SNAPSHOT/neodatis-odb-1.9-SNAPSHOT.jar:\
$HOME/.m2/repository/pircbot/pircbot/1.4.2/pircbot-1.4.2.jar:\
$HOME/.m2/repository/jivesoftware/smack/3.0.4/smack-3.0.4.jar:\
$HOME/.m2/repository/jivesoftware/smackx/3.0.4/smackx-3.0.4.jar:\
$HOME/.m2/repository/scala/project/tools/scala.project.tools/1.0-SNAPSHOT/scala.project.tools-1.0-SNAPSHOT.jar \
$main "${YOUR_CONFIG_FILENAME}" $2 $3

updateVersion