#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

main="deployer.Deployer"
arg="project.tools.xml"
args="$arg $*"

cd `dirname $0`
cd ../project.tools/ide_projects/continuous.tools
mvn -e exec:java -Dexec.mainClass=$main -Dexec.args="$args"

exit
