#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

main="jar.comparator.GiveCRC"

# $1 - path to file to be checked
# $2 - dir to this script (project.tools dir)
# $3 - path to scala bin

$2 -classpath \
$HOME/.m2/repository/org/scala-lang/scala-library/2.7.5/scala-library-2.7.5.jar:\
$HOME/.m2/repository/scala/project/tools/scala.project.tools/1.0-SNAPSHOT/scala.project.tools-1.0-SNAPSHOT.jar \
$main $1
