#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

set -x
. OPTS

cd src/
mvn install -Dmaven.test.skip.exec=true $@
echo "Hit Enter to perform tests, SIGINT to terminate"
read
mvn test -o
