#!/bin/sh

BSDMAKE_BIN="/usr/bin/make"
MERGEMASTER_BIN="/usr/sbin/mergemaster"

check_result () {
  if [ "$1" != "0" ]; then
    echo "FAILURE"
    exit 666
  fi
}


cd /usr/src
echo "Merging master"
${MERGEMASTER_BIN} -pF
check_result $?

echo "Installing world"
${BSDMAKE_BIN} installworld
check_result $?

echo "Final merge"
${MERGEMASTER_BIN} -F
check_result $?

echo "Deleting old files"
${BSDMAKE_BIN} -DBATCH_DELETE_OLD_FILES delete-old delete-old-libs
check_result $?

echo "Done. Base system installed. We're ready for last stage…"
