#!/bin/sh

LOGIN_CONF_FILE="/etc/login.conf"
CSUP_BIN="/usr/bin/csup"
BSDMAKE_BIN="/usr/bin/make"
READ_BIN="/usr/bin/read"
REBOOT_BIN="/sbin/reboot"
PWD_BIN="/bin/pwd"
CP_BIN="/bin/cp"
DATE_BIN="/bin/date"
MKDIR_BIN="/bin/mkdir"
TIME_BIN="/usr/bin/time"
WHICH_BIN="/usr/bin/which"
RM_BIN="/bin/rm"

KERNEL_CONFIG_PATH="/usr/src/sys/amd64/conf/"
PREFILES="$(${PWD_BIN})/prefiles/"


check_result () {
  if [ "$1" != "0" ]; then
    echo "FAILURE"
    exit 666
  fi
}


echo "Looking for GIT SCM"
${WHICH_BIN} git
check_result $?

if [ ! -d "/usr/src/sys" ]; then
  echo "No system sources found"
  ${RM_BIN} -rf /usr/src
  cd /usr
  echo "Cloning FreeBSD base system"
  ${TIME_BIN} git clone git://github.com/VerKnowSys/freebsd.git src
  cd src
  git checkout releng/9.1
else
  echo "Updating kernel source"
  cd /usr/src
  ${TIME_BIN} git pull
fi

echo "Copying VERKNOWSYS kernel config to ${KERNEL_CONFIG_PATH}"
${CP_BIN} $(${PWD_BIN})/kernel/VerKnowSys ${KERNEL_CONFIG_PATH}VerKnowSys

echo "Building world"

unset LDFLAGS
unset LD_LIBRARY_PATH
unset CXXFLAGS
unset CFLAGS
unset PATH

cd /usr/src
${TIME_BIN} $BSDMAKE_BIN -j8 buildworld
check_result $?

${TIME_BIN} $BSDMAKE_BIN buildkernel KERNCONF=VerKnowSys
check_result $?

datenow="$(${DATE_BIN} +"%y_%m_%d-%H_%M_%S")"
oldkernel_dir="/boot/kernel_old_${datenow}"
echo "Making copy of actual kernel to: ${oldkernel_dir}"
${MKDIR_BIN} -p ${oldkernel_dir}
${CP_BIN} -r /boot/kernel ${oldkernel_dir}

echo "Installing kernel"
${TIME_BIN} $BSDMAKE_BIN installkernel KERNCONF=VerKnowSys
check_result $?

echo "Reboot is required to run new kernel, after which You need to execute STAGE-TWO script"
echo "... If you're believer, you may start to pray now."
echo
echo "[Hit Enter to reboot machine]"
${READ_BIN} reply
${REBOOT_BIN}
