#!/bin/sh

LN_BIN="/bin/ln"
RM_BIN="/bin/rm"
MV_BIN="/bin/mv"
MKDIR_BIN="/bin/mkdir"
SERVICE_BIN="/usr/sbin/service"
MKDB_SERVICES_BIN="/usr/sbin/services_mkdb"
MKDB_CAP_BIN="/usr/bin/cap_mkdb"
PWD_MKDB="/usr/sbin/pwd_mkdb"
PW_BIN="/usr/sbin/pw"
CHFLAGS_BIN="/bin/chflags"
PWD_BIN="/bin/pwd"

SSH_AUTH_KEYS="
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxWWFZVKHKUOgQiO7C/sClpYInJr7nkWAkld94s5QY03kxbOOx862IELwssnt0K+Yrm8LJqZr+adP5/s98hT3bJ2FTdSqm5FaJT+YHUNJlsG4ufRBxtjuYlHH++uYjfBnl66T31L6E3yQJuxYtC0dzIU12TEsFtAQotWgwwcI3ioPnjOQtgY0eWW9yhrnR6m5k5NMQKbrJK5wXC1PzwL3fa3G3XyD5f5ZrFUf6T30EUJs7J0Tvo1hGI1xUWNXK3E2RBlCwcOFYjom71XyE5q7iuY42AbCI25ttFOk1r/zjhXSxNEoTf+3bO0W/LlBUo9DRECE1AtTnYQmSU1tYU6TsQ== dmilith@macbook-pro-daniel-dettlaff.local
"

RMLIST="/usr/bin/newaliases
/usr/bin/write
/usr/bin/wall
/usr/bin/ypcat
/usr/bin/ypchfn
/usr/bin/ypchpass
/usr/bin/ypchsh
/usr/bin/ypmatch
/usr/bin/yppasswd
/usr/bin/ypwhich
/usr/sbin/yp_mkdb
/usr/sbin/ypbind
/usr/sbin/ypinit
/usr/sbin/yppoll
/usr/sbin/yppush
/usr/sbin/ypserv
/usr/sbin/ypset
/etc/periodic
/usr/libexec/sendmail
/mnt
/proc
/srv
/cdrom
/home
/COPYRIGHT
/etc/bluetooth
/etc/rc.d/sendmail
/etc/mail
/etc/X11
/etc/csh.*
/etc/ftpusers
/etc/hosts.lpd
/etc/mail.rc
/usr/sbin/sendmail
/usr/bin/mail
/var/mail
/etc/defaults/blue*
/etc/defaults/periodic*
/etc/gnats
/etc/ppp
/etc/skel
/etc/sudoers.d
/usr/games
/usr/local
/usr/share/games
/usr/share/sendmail
/usr/include/objc
/usr/share/examples/libdialog
/usr/share/examples/dialog
/usr/share/examples/bc
/usr/include/netgraph/bluetooth/include
/usr/include/netgraph/bluetooth
/usr/share/man/man9/vm_page_flag.9.gz
/usr/share/man/man9/vm_page_flag_clear.9.gz
/usr/share/man/man9/vm_page_flag_set.9.gz
/usr/sbin/named.reconfig
/usr/sbin/named.reload
/usr/share/man/man9/vm_map_clean.9.gz
/usr/share/man/man9/vm_page_copy.9.gz
/usr/share/man/man9/vm_page_protect.9.gz
/usr/share/man/man9/vm_page_zero_fill.9.gz
/etc/rc.d/nfsserver
/usr/include/nfsclient/krpc.h
/usr/include/nfsclient/nfsdiskless.h
/sbin/mount_newnfs
/usr/share/man/man8/mount_newnfs.8.gz
/usr/include/nfsclient/nfs_kdtrace.h
/usr/share/calendar/ru_RU.KOI8-R/calendar.msk
/usr/share/examples/kld/firmware/fwimage/firmware.img
/usr/share/man/man8/sticky.8.gz
/usr/include/netinet/sctp_cc_functions.h
/usr/share/man/man9/SYSCTL_XINT.9.gz
/usr/share/man/man9/SYSCTL_XLONG.9.gz
/usr/share/man/man3/draw_shadow.3.gz
/usr/share/man/man3/draw_box.3.gz
/usr/share/man/man3/line_edit.3.gz
/usr/share/man/man3/strheight.3.gz
/usr/share/man/man3/strwidth.3.gz
/usr/share/man/man3/dialog_create_rc.3.gz
/usr/share/man/man3/dialog_yesno.3.gz
/usr/share/man/man3/dialog_noyes.3.gz
/usr/share/man/man3/dialog_prgbox.3.gz
/usr/share/man/man3/dialog_textbox.3.gz
/usr/share/man/man3/dialog_menu.3.gz
/usr/share/man/man3/dialog_checklist.3.gz
/usr/share/man/man3/dialog_radiolist.3.gz
/usr/share/man/man3/dialog_inputbox.3.gz
/usr/share/man/man3/dialog_clear_norefresh.3.gz
/usr/share/man/man3/dialog_clear.3.gz
/usr/share/man/man3/dialog_update.3.gz
/usr/share/man/man3/dialog_fselect.3.gz
/usr/share/man/man3/dialog_notify.3.gz
/usr/share/man/man3/dialog_mesgbox.3.gz
/usr/share/man/man3/dialog_gauge.3.gz
/usr/share/man/man3/init_dialog.3.gz
/usr/share/man/man3/end_dialog.3.gz
/usr/share/man/man3/use_helpfile.3.gz
/usr/share/man/man3/use_helpline.3.gz
/usr/share/man/man3/get_helpline.3.gz
/usr/share/man/man3/restore_helpline.3.gz
/usr/share/man/man3/dialog_msgbox.3.gz
/usr/share/man/man3/dialog_ftree.3.gz
/usr/share/man/man3/dialog_tree.3.gz
/usr/share/examples/dialog/README
/usr/share/examples/dialog/checklist
/usr/share/examples/dialog/ftreebox
/usr/share/examples/dialog/infobox
/usr/share/examples/dialog/inputbox
/usr/share/examples/dialog/menubox
/usr/share/examples/dialog/msgbox
/usr/share/examples/dialog/prgbox
/usr/share/examples/dialog/radiolist
/usr/share/examples/dialog/textbox
/usr/share/examples/dialog/treebox
/usr/share/examples/dialog/yesno
/usr/share/examples/libdialog/Makefile
/usr/share/examples/libdialog/check1.c
/usr/share/examples/libdialog/check2.c
/usr/share/examples/libdialog/check3.c
/usr/share/examples/libdialog/dselect.c
/usr/share/examples/libdialog/fselect.c
/usr/share/examples/libdialog/ftree1.c
/usr/share/examples/libdialog/ftree1.test
/usr/share/examples/libdialog/ftree2.c
/usr/share/examples/libdialog/ftree2.test
/usr/share/examples/libdialog/gauge.c
/usr/share/examples/libdialog/input1.c
/usr/share/examples/libdialog/input2.c
/usr/share/examples/libdialog/menu1.c
/usr/share/examples/libdialog/menu2.c
/usr/share/examples/libdialog/menu3.c
/usr/share/examples/libdialog/msg.c
/usr/share/examples/libdialog/prgbox.c
/usr/share/examples/libdialog/radio1.c
/usr/share/examples/libdialog/radio2.c
/usr/share/examples/libdialog/radio3.c
/usr/share/examples/libdialog/text.c
/usr/share/examples/libdialog/tree.c
/usr/share/examples/libdialog/yesno.c
/usr/share/info/gasp.info.gz
/usr/share/man/man9/taskqueue_find.9.gz
/etc/manpath.config
/usr/share/examples/etc/manpath.config
/usr/share/man/man9/sbuf_overflowed.9.gz
/usr/share/man/man9/chooseproc.9.gz
/usr/share/man/man3/ascftime.3.gz
/usr/share/man/man3/cfree.3.gz
/usr/share/man/man3/cftime.3.gz
/usr/share/man/man3/getpw.3.gz
/usr/share/man/man4/acpi_aiboost.4.gz
/usr/share/man/man3/regexp.3.gz
/usr/share/man/man3/regsub.3.gz
/usr/share/examples/bc/ckbook.b
/usr/share/examples/bc/pi.b
/usr/share/examples/bc/primes.b
/usr/share/examples/bc/twins.b
/usr/share/info/dc.info.gz
/usr/share/man/man3/ttyslot.3.gz
/usr/share/man/man3/login.3.gz
/usr/share/man/man3/logout.3.gz
/usr/share/man/man3/logwtmp.3.gz
/usr/share/man/man5/lastlog.5.gz
/usr/share/man/man5/utmp.5.gz
/usr/share/man/man5/wtmp.5.gz
/usr/sbin/ntptrace
/usr/share/man/man8/ntptrace.8.gz
/usr/share/zoneinfo/GMT
/etc/mtree/BSD.local.dist
/etc/mtree/BSD.x11.dist
/etc/mtree/BSD.x11-4.dist
/usr/share/man/man9/MULTI_DRIVER_MODULE.9.gz
/usr/bin/at
/usr/bin/atq
/usr/bin/atrm
/usr/bin/batch
/usr/libexec/atrun
/usr/share/man/man1/at.1.gz
/usr/share/man/man1/atq.1.gz
/usr/share/man/man1/atrm.1.gz
/usr/share/man/man1/batch.1.gz
/usr/share/man/man8/atrun.8.gz
/etc/bluetooth/hcsecd.conf
/etc/bluetooth/hosts
/etc/bluetooth/protocols
/usr/bin/bthost
/usr/bin/btsockstat
/usr/bin/rfcomm_sppd
/usr/include/bluetooth.h
/usr/include/netgraph/bluetooth/include/ng_bluetooth.h
/usr/include/netgraph/bluetooth/include/ng_bt3c.h
/usr/include/netgraph/bluetooth/include/ng_btsocket.h
/usr/include/netgraph/bluetooth/include/ng_btsocket_hci_raw.h
/usr/include/netgraph/bluetooth/include/ng_btsocket_l2cap.h
/usr/include/netgraph/bluetooth/include/ng_btsocket_rfcomm.h
/usr/include/netgraph/bluetooth/include/ng_btsocket_sco.h
/usr/include/netgraph/bluetooth/include/ng_h4.h
/usr/include/netgraph/bluetooth/include/ng_hci.h
/usr/include/netgraph/bluetooth/include/ng_l2cap.h
/usr/include/netgraph/bluetooth/include/ng_ubt.h
/usr/lib/libbluetooth.a
/usr/lib/libbluetooth.so
/usr/lib/libbluetooth_p.a
/usr/lib32/libbluetooth.a
/usr/lib32/libbluetooth.so
/usr/lib32/libbluetooth_p.a
/usr/sbin/bcmfw
/usr/sbin/bt3cfw
/usr/sbin/bthidcontrol
/usr/sbin/bthidd
/usr/sbin/btpand
/usr/sbin/hccontrol
/usr/sbin/hcsecd
/usr/sbin/hcseriald
/usr/sbin/l2control
/usr/sbin/l2ping
/usr/sbin/rfcomm_pppd
/usr/sbin/sdpcontrol
/usr/sbin/sdpd
/usr/share/man/man1/bthost.1.gz
/usr/share/man/man1/btsockstat.1.gz
/usr/share/man/man1/rfcomm_sppd.1.gz
/usr/share/man/man3/SDP_GET128.3.gz
/usr/share/man/man3/SDP_GET16.3.gz
/usr/share/man/man3/SDP_GET32.3.gz
/usr/share/man/man3/SDP_GET64.3.gz
/usr/share/man/man3/SDP_GET8.3.gz
/usr/share/man/man3/SDP_PUT128.3.gz
/usr/share/man/man3/SDP_PUT16.3.gz
/usr/share/man/man3/SDP_PUT32.3.gz
/usr/share/man/man3/SDP_PUT64.3.gz
/usr/share/man/man3/SDP_PUT8.3.gz
/usr/share/man/man3/bdaddr_any.3.gz
/usr/share/man/man3/bdaddr_copy.3.gz
/usr/share/man/man3/bdaddr_same.3.gz
/usr/share/man/man3/bluetooth.3.gz
/usr/share/man/man3/bt_aton.3.gz
/usr/share/man/man3/bt_devaddr.3.gz
/usr/share/man/man3/bt_devclose.3.gz
/usr/share/man/man3/bt_devenum.3.gz
/usr/share/man/man3/bt_devfilter.3.gz
/usr/share/man/man3/bt_devfilter_evt_clr.3.gz
/usr/share/man/man3/bt_devfilter_evt_set.3.gz
/usr/share/man/man3/bt_devfilter_evt_tst.3.gz
/usr/share/man/man3/bt_devfilter_pkt_clr.3.gz
/usr/share/man/man3/bt_devfilter_pkt_set.3.gz
/usr/share/man/man3/bt_devfilter_pkt_tst.3.gz
/usr/share/man/man3/bt_devinfo.3.gz
/usr/share/man/man3/bt_devinquiry.3.gz
/usr/share/man/man3/bt_devname.3.gz
/usr/share/man/man3/bt_devopen.3.gz
/usr/share/man/man3/bt_devreq.3.gz
/usr/share/man/man3/bt_devsend.3.gz
/usr/share/man/man3/bt_endhostent.3.gz
/usr/share/man/man3/bt_endprotoent.3.gz
/usr/share/man/man3/bt_gethostbyaddr.3.gz
/usr/share/man/man3/bt_gethostbyname.3.gz
/usr/share/man/man3/bt_gethostent.3.gz
/usr/share/man/man3/bt_getprotobyname.3.gz
/usr/share/man/man3/bt_getprotobynumber.3.gz
/usr/share/man/man3/bt_getprotoent.3.gz
/usr/share/man/man3/bt_ntoa.3.gz
/usr/share/man/man3/bt_sethostent.3.gz
/usr/share/man/man3/bt_setprotoent.3.gz
/usr/share/man/man3/sdp.3.gz
/usr/share/man/man3/sdp_attr2desc.3.gz
/usr/share/man/man3/sdp_change_service.3.gz
/usr/share/man/man3/sdp_close.3.gz
/usr/share/man/man3/sdp_error.3.gz
/usr/share/man/man3/sdp_open.3.gz
/usr/share/man/man3/sdp_open_local.3.gz
/usr/share/man/man3/sdp_register_service.3.gz
/usr/share/man/man3/sdp_search.3.gz
/usr/share/man/man3/sdp_unregister_service.3.gz
/usr/share/man/man3/sdp_uuid2desc.3.gz
/usr/share/man/man5/hcsecd.conf.5.gz
/usr/share/man/man8/bcmfw.8.gz
/usr/share/man/man8/bt3cfw.8.gz
/usr/share/man/man8/bthidcontrol.8.gz
/usr/share/man/man8/bthidd.8.gz
/usr/share/man/man8/btpand.8.gz
/usr/share/man/man8/hccontrol.8.gz
/usr/share/man/man8/hcsecd.8.gz
/usr/share/man/man8/hcseriald.8.gz
/usr/share/man/man8/l2control.8.gz
/usr/share/man/man8/l2ping.8.gz
/usr/share/man/man8/rfcomm_pppd.8.gz
/usr/share/man/man8/sdpcontrol.8.gz
/usr/share/man/man8/sdpd.8.gz
/etc/periodic/daily/300.calendar
/usr/bin/calendar
/usr/share/calendar/calendar.all
/usr/share/calendar/calendar.australia
/usr/share/calendar/calendar.birthday
/usr/share/calendar/calendar.christian
/usr/share/calendar/calendar.computer
/usr/share/calendar/calendar.croatian
/usr/share/calendar/calendar.dutch
/usr/share/calendar/calendar.freebsd
/usr/share/calendar/calendar.french
/usr/share/calendar/calendar.german
/usr/share/calendar/calendar.history
/usr/share/calendar/calendar.holiday
/usr/share/calendar/calendar.hungarian
/usr/share/calendar/calendar.judaic
/usr/share/calendar/calendar.lotr
/usr/share/calendar/calendar.music
/usr/share/calendar/calendar.newzealand
/usr/share/calendar/calendar.russian
/usr/share/calendar/calendar.southafrica
/usr/share/calendar/calendar.ukrainian
/usr/share/calendar/calendar.usholiday
/usr/share/calendar/calendar.world
/usr/share/calendar/de_AT.ISO_8859-15/calendar.feiertag
/usr/share/calendar/de_DE.ISO8859-1/calendar.all
/usr/share/calendar/de_DE.ISO8859-1/calendar.feiertag
/usr/share/calendar/de_DE.ISO8859-1/calendar.geschichte
/usr/share/calendar/de_DE.ISO8859-1/calendar.kirche
/usr/share/calendar/de_DE.ISO8859-1/calendar.literatur
/usr/share/calendar/de_DE.ISO8859-1/calendar.musik
/usr/share/calendar/de_DE.ISO8859-1/calendar.wissenschaft
/usr/share/calendar/de_DE.ISO8859-15
/usr/share/calendar/fr_FR.ISO8859-1/calendar.all
/usr/share/calendar/fr_FR.ISO8859-1/calendar.fetes
/usr/share/calendar/fr_FR.ISO8859-1/calendar.french
/usr/share/calendar/fr_FR.ISO8859-1/calendar.jferies
/usr/share/calendar/fr_FR.ISO8859-1/calendar.proverbes a
/usr/share/calendar/fr_FR.ISO8859-15
/usr/share/calendar/hr_HR.ISO8859-2/calendar.all
/usr/share/calendar/hr_HR.ISO8859-2/calendar.praznici
/usr/share/calendar/hu_HU.ISO8859-2/calendar.all
/usr/share/calendar/hu_HU.ISO8859-2/calendar.nevnapok
/usr/share/calendar/hu_HU.ISO8859-2/calendar.unnepek
/usr/share/calendar/ru_RU.KOI8-R/calendar.all
/usr/share/calendar/ru_RU.KOI8-R/calendar.common
/usr/share/calendar/ru_RU.KOI8-R/calendar.holiday
/usr/share/calendar/ru_RU.KOI8-R/calendar.military
/usr/share/calendar/ru_RU.KOI8-R/calendar.orthodox
/usr/share/calendar/ru_RU.KOI8-R/calendar.pagan
/usr/share/calendar/uk_UA.KOI8-U/calendar.all
/usr/share/calendar/uk_UA.KOI8-U/calendar.holiday
/usr/share/calendar/uk_UA.KOI8-U/calendar.misc
/usr/share/calendar/uk_UA.KOI8-U/calendar.orthodox
/usr/share/man/man1/calendar.1.gz
/usr/share/dict/README
/usr/share/dict/freebsd
/usr/share/dict/propernames
/usr/share/dict/web2
/usr/share/dict/web2a
/usr/share/dict/words
/usr/sbin/fdcontrol
/usr/sbin/fdformat
/usr/sbin/fdread
/usr/sbin/fdwrite
/usr/share/man/man1/fdformat.1.gz
/usr/share/man/man1/fdread.1.gz
/usr/share/man/man1/fdwrite.1.gz
/usr/share/man/man8/fdcontrol.8.gz
/usr/games/bcd
/usr/games/caesar
/usr/games/factor
/usr/games/fortune
/usr/games/grdc
/usr/games/morse
/usr/games/number
/usr/games/pom
/usr/games/ppt
/usr/games/primes
/usr/games/random
/usr/games/rot13
/usr/games/strfile
/usr/games/unstr
/usr/share/games/fortune/fortunes
/usr/share/games/fortune/fortunes-o
/usr/share/games/fortune/fortunes-o.dat
/usr/share/games/fortune/fortunes.dat
/usr/share/games/fortune/freebsd-tips
/usr/share/games/fortune/freebsd-tips.dat
/usr/share/games/fortune/gerrold.limerick
/usr/share/games/fortune/gerrold.limerick.dat
/usr/share/games/fortune/limerick
/usr/share/games/fortune/limerick.dat
/usr/share/games/fortune/murphy
/usr/share/games/fortune/murphy-o
/usr/share/games/fortune/murphy-o.dat
/usr/share/games/fortune/murphy.dat
/usr/share/games/fortune/startrek
/usr/share/games/fortune/startrek.dat
/usr/share/games/fortune/zippy
/usr/share/games/fortune/zippy.dat
/usr/share/man/man6/bcd.6.gz
/usr/share/man/man6/caesar.6.gz
/usr/share/man/man6/factor.6.gz
/usr/share/man/man6/fortune.6.gz
/usr/share/man/man6/grdc.6.gz
/usr/share/man/man6/morse.6.gz
/usr/share/man/man6/number.6.gz
/usr/share/man/man6/pom.6.gz
/usr/share/man/man6/ppt.6.gz
/usr/share/man/man6/primes.6.gz
/usr/share/man/man6/random.6.gz
/usr/share/man/man6/rot13.6.gz
/usr/share/man/man8/strfile.8.gz
/usr/share/man/man8/unstr.8.gz
/etc/periodic/security/500.ipfwdenied
/etc/periodic/security/550.ipfwlimit
/sbin/ipfw
/sbin/natd /usr/sbin/ipfwpcap
/usr/share/man/man8/ipfw.8.gz
/usr/share/man/man8/ipfwpcap.8.gz
/usr/share/man/man8/natd.8.gz
/usr/lib/libipx.a
/usr/lib/libipx.so
/usr/lib/libipx_p.a
/usr/lib32/libipx.a
/usr/lib32/libipx.so
/usr/lib32/libipx_p.a
/usr/sbin/IPXrouted
/usr/share/man/man3/ipx.3.gz
/usr/share/man/man3/ipx_addr.3.gz
/usr/share/man/man3/ipx_ntoa.3.gz
/usr/share/man/man8/IPXrouted.8.gz
/etc/locate.rc
/etc/periodic/weekly/310.locate
/usr/bin/locate
/usr/libexec/locate.bigram
/usr/libexec/locate.code
/usr/libexec/locate.concatdb
/usr/libexec/locate.mklocatedb
/usr/libexec/locate.updatedb
/usr/share/man/man1/locate.1.gz
/usr/share/man/man8/locate.updatedb.8.gz
/usr/share/man/man8/updatedb.8.gz
/etc/hosts.lpd
/etc/printcap
/usr/bin/lp
/usr/bin/lpq
/usr/bin/lpr
/usr/bin/lprm
/usr/libexec/lpr/ru/bjc-240.sh.sample
/usr/libexec/lpr/ru/koi2alt
/usr/libexec/lpr/ru/koi2855
/usr/libexec/lpr/lpf
/usr/sbin/chkprintcap
/usr/sbin/lpc
/usr/sbin/lpd
/usr/sbin/lptest
/usr/sbin/pac
/usr/share/doc/smm/07.lpd/paper.ascii.gz /usr/share/examples/etc/hosts.lpd
/usr/share/examples/etc/printcap
/usr/share/man/man1/lp.1.gz
/usr/share/man/man1/lpq.1.gz
/usr/share/man/man1/lpr.1.gz
/usr/share/man/man1/lprm.1.gz
/usr/share/man/man1/lptest.1.gz
/usr/share/man/man5/printcap.5.gz
/usr/share/man/man8/chkprintcap.8.gz
/usr/share/man/man8/lpc.8.gz
/usr/share/man/man8/lpd.8.gz
/usr/share/man/man8/pac.8.gz
/etc/periodic/daily/130.clean-msgs
/usr/bin/Mail
/usr/bin/biff
/usr/bin/from
/usr/bin/mail
/usr/bin/mailx
/usr/bin/msgs
/usr/libexec/comsat
/usr/share/examples/etc/mail.rc
/usr/share/man/man1/Mail.1.gz
/usr/share/man/man1/biff.1.gz
/usr/share/man/man1/from.1.gz
/usr/share/man/man1/mail.1.gz
/usr/share/man/man1/mailx.1.gz
/usr/share/man/man1/msgs.1.gz
/usr/share/man/man8/comsat.8.gz
/usr/share/misc/mail.help
/usr/share/misc/mail.tildehelp
/etc/mail/mailer.conf
/usr/sbin/mailwrapper
/usr/share/man/man8/mailwrapper.8.gz
/usr/bin/ncplist
/usr/bin/ncplogin
/usr/bin/ncplogout
/usr/include/fs/nwfs/nwfs.h /usr/include/fs/nwfs/nwfs_mount.h
/usr/include/fs/nwfs/nwfs_node.h
/usr/include/fs/nwfs/nwfs_subr.h
/usr/include/netncp/ncp.h
/usr/include/netncp/ncp_cfg.h
/usr/include/netncp/ncp_conn.h
/usr/include/netncp/ncp_file.h
/usr/include/netncp/ncp_lib.h
/usr/include/netncp/ncp_ncp.h
/usr/include/netncp/ncp_nls.h
/usr/include/netncp/ncp_rcfile.h
/usr/include/netncp/ncp_rq.h
/usr/include/netncp/ncp_sock.h
/usr/include/netncp/ncp_subr.h
/usr/include/netncp/ncp_user.h
/usr/include/netncp/ncpio.h
/usr/include/netncp/nwerror.h
/usr/lib/libncp.a
/usr/lib/libncp.so
/usr/lib/libncp_p.a
/usr/lib32/libncp.a
/usr/lib32/libncp.so
/usr/lib32/libncp_p.a
/usr/sbin/mount_nwfs
/usr/share/man/man1/ncplist.1.gz
/usr/share/man/man1/ncplogin.1.gz
/usr/share/man/man1/ncplogout.1.gz
/usr/share/man/man8/mount_nwfs.8.gz
/bin/rcp
/rescue/rcp
/usr/bin/rlogin
/usr/bin/rsh
/usr/bin/ruptime
/usr/bin/rwho
/usr/libexec/rlogind
/usr/libexec/rshd
/usr/sbin/rwhod
/usr/share/man/man1/rcp.1.gz
/usr/share/man/man1/rlogin.1.gz
/usr/share/man/man1/rsh.1.gz
/usr/share/man/man1/ruptime.1.gz
/usr/share/man/man1/rwho.1.gz
/usr/share/man/man8/rlogind.8.gz
/usr/share/man/man8/rshd.8.gz
/usr/share/man/man8/rwhod.8.gz
/bin/rmail
/usr/bin/vacation
/usr/include/libmilter/mfapi.h
/usr/include/libmilter/mfdef.h
/usr/lib/libmilter.a
/usr/lib/libmilter_p.a
/usr/lib32/libmilter.a
/usr/lib32/libmilter_p.a
/usr/libexec/mail.local
/usr/libexec/sendmail/sendmail /usr/libexec/smrsh
/usr/sbin/editmap
/usr/sbin/mailstats
/usr/sbin/makemap
/usr/sbin/praliases
/usr/share/doc/smm/08.sendmailop/paper.ascii.gz
/usr/share/man/man1/mailq.1.gz
/usr/share/man/man1/newaliases.1.gz
/usr/share/man/man1/vacation.1.gz
/usr/share/man/man5/aliases.5.gz
/usr/share/man/man8/editmap.8.gz
/usr/share/man/man8/hoststat.8.gz
/usr/share/man/man8/mail.local.8.gz
/usr/share/man/man8/mailstats.8.gz
/usr/share/man/man8/makemap.8.gz
/usr/share/man/man8/praliases.8.gz
/usr/share/man/man8/purgestat.8.gz
/usr/share/man/man8/rmail.8.gz
/usr/share/man/man8/sendmail.8.gz
/usr/share/man/man8/smrsh.8.gz
/etc/regdomain.xml
/usr/sbin/ancontrol
/usr/sbin/hostapd
/usr/sbin/hostapd_cli
/usr/sbin/ndis_events
/usr/sbin/wlandebug
/usr/sbin/wpa_cli
/usr/sbin/wpa_passphrase
/usr/sbin/wpa_supplicant
/usr/share/examples/etc/regdomain.xml
/usr/share/examples/etc/wpa_supplicant.conf
/usr/share/examples/hostapd/hostapd.conf
/usr/share/examples/hostapd/hostapd.eap_user
/usr/share/examples/hostapd/hostapd.wpa_psk
/usr/share/man/man5/hostapd.conf.5.gz
/usr/share/man/man5/wpa_supplicant.conf.5.gz
/usr/share/man/man8/ancontrol.8.gz
/usr/share/man/man8/hostapd.8.gz
/usr/share/man/man8/hostapd_cli.8.gz
/usr/share/man/man8/ndis_events.8.gz
/usr/share/man/man8/wlandebug.8.gz
/usr/share/man/man8/wpa_cli.8.gz
/usr/share/man/man8/wpa_passphrase.8.gz
/usr/share/man/man8/wpa_supplicant.8.gz
/var/games
/var/at
/media
/.cshrc
/.profile
"

for i in ${RMLIST}; do
   echo "Removing: $i"
   ${CHFLAGS_BIN} noschg "${i}"
   ${RM_BIN} -rf "${i}"
done

echo "Linking Linux fallback commands"
${LN_BIN} -s /usr/bin/lockf /usr/bin/flock
${LN_BIN} -s /bin/sh /bin/bash

echo "Moving rescue system"
${MV_BIN} /rescue /usr/rescue > /dev/null

echo "Moving additional utilities to /usr/rescue"
${MV_BIN} /usr/bin/su /usr/rescue/su
${MV_BIN} /usr/bin/w /usr/rescue/w
${MV_BIN} /usr/bin/who /usr/rescue/who

echo "Preparing passwd & group"
${PW_BIN} usermod root -d /usr/root
${MKDIR_BIN} -p /usr/root/.ssh
echo "${SSH_AUTH_KEYS}" > /usr/root/.ssh/authorized_keys

echo "root:*:0:0:Charlie &:/usr/root:/bin/sh
nobody:*:1:1:Unprivileged user:/nonexistent:/usr/sbin/nologin
" > /etc/passwd

echo "wheel:*:0:root
nobody:*:1:
nogroup:*:2:
audit:*:3:
proxy:*:4:
authpf:*:5:
tty:*:6:
operator:*:7:
games:*:8:
bind:*:9:
kmem:*:10:
daemon:*:11:
" > /etc/group

echo "Generating master.passwd"
${PWD_MKDB} /etc/master.passwd


echo "Setting up sshd"

echo "
Host verknowsys.com *.verknowsys.com
Port 60022
" > /etc/ssh/ssh_config

echo "Port 60022
UsePAM no
X11Forwarding no
PrintMotd yes
PrintLastLog yes
TCPKeepAlive yes
UseLogin yes
PermitUserEnvironment yes
Compression delayed
ClientAliveInterval 60
ClientAliveCountMax 3
UseDNS no
RSAAuthentication yes
PubkeyAuthentication yes
PasswordAuthentication yes
PermitRootLogin yes
Subsystem	sftp	/usr/libexec/sftp-server
" > /etc/ssh/sshd_config

echo "Updating login db…"
${MKDB_CAP_BIN} /etc/login.conf

echo "Updating services db…"
${MKDB_SERVICES_BIN} -q -o /var/db/services.db /etc/services

echo "Restarting services"
${SERVICE_BIN} sshd restart
