#!/bin/sh

BSD_VERSION="RELENG_9_0"
DEFAULT_SOURCE="cvsup.cz.FreeBSD.org"
CSUP_FILE="/etc/csup"
LOGIN_CONF_FILE="/etc/login.conf"
SRC_CONF_FILE="/etc/src.conf"
MAKE_CONF_FILE="/etc/make.conf"
READ_BIN="/usr/bin/read"
PWD_BIN="/bin/pwd"
CP_BIN="/bin/cp"
CAP_MKDB="/usr/bin/cap_mkdb"

KERNEL_CONFIG_PATH="/usr/src/sys/amd64/conf/"
PREFILES="$(${PWD_BIN})/prefiles/"
LOG="$(${PWD_BIN})/STAGE-ONE.log"


echo "Creating ${LOGIN_CONF_FILE}"
echo "
default:\\
  :charset=UTF-8:\\
  :lang=pl_PL.UTF-8:\\
  :passwd_format=md5:\\
  :copyright=/etc/COPYRIGHT:\\
  :welcome=/etc/motd:\\
  :setenv=MAIL=/var/mail/$,BLOCKSIZE=K,FTP_PASSIVE_MODE=YES,LC_COLLATE=C:\\
  :path=/sbin /bin /usr/sbin /usr/bin ~/Apps:\\
  :nologin=/var/run/nologin:\\
  :cputime=unlimited:\\
  :datasize=unlimited:\\
  :stacksize=unlimited:\\
  :memorylocked=unlimited:\\
  :memoryuse=unlimited:\\
  :filesize=unlimited:\\
  :coredumpsize=unlimited:\\
  :openfiles=unlimited:\\
  :maxproc=unlimited:\\
  :sbsize=unlimited:\\
  :vmemoryuse=unlimited:\\
  :swapuse=unlimited:\\
  :pseudoterminals=unlimited:\\
  :priority=0:\\
  :ignoretime@:\\
  :umask=022:

standard:\\
  :tc=default:
xuser:\\
  :tc=default:
staff:\\
  :tc=default:
daemon:\\
  :tc=default:
news:\\
  :tc=default:
dialer:\\
  :tc=default:

#
root:\\
  :ignorenologin:\\
  :tc=default:
" > "${LOGIN_CONF_FILE}"

echo "Reloading login rules"
${CAP_MKDB} -v ${LOGIN_CONF_FILE}

echo "Creating ${CSUP_FILE}"
echo "
*default host=${DEFAULT_SOURCE}
*default base=/var/db
*default prefix=/usr
*default release=cvs tag=${BSD_VERSION}
*default delete use-rel-suffix
*default compress
src-all
" > "${CSUP_FILE}"


echo "Creating ${SRC_CONF_FILE}"
echo "
WITHOUT_CALENDAR='YES'
WITHOUT_GAMES='YES'
WITHOUT_IPX='YES'
WITHOUT_IPX_SUPPORT='YES'
WITHOUT_IPFW='YES'
WITHOUT_INFO='YES'
WITHOUT_HTML='YES'
WITHOUT_FLOPPY='YES'
WITHOUT_EXAMPLES='YES'
WITHOUT_DICT='YES'
WITHOUT_LPR='YES'
WITHOUT_AT='YES'
WITHOUT_ASSERT_DEBUG='YES'
WITHOUT_SENDMAIL='YES'
WITHOUT_RCMDS='YES'
WITHOUT_WPA_SUPPLICANT_EAPOL='YES'
WITHOUT_BLUETOOTH='YES'
WITHOUT_MAIL='YES'
WITHOUT_USB='YES'
WITHOUT_WIRELESS='YES'
WITHOUT_WIRELESS_SUPPORT='YES'
WITHOUT_MAILWRAPPER='YES'
WITHOUT_LOCATE='YES'
WITHOUT_SOUND='YES'
WITHOUT_NFS='YES'
WITHOUT_EXAMPLES='YES'
WITHOUT_CTM='YES'
WITHOUT_LEGACY_CONSOLE='YES'
WITHOUT_LOCALES='YES'
WITHOUT_LOCATE='YES'
WITHOUT_NLS='YES'
WITHOUT_NLS_CATALOGS='YES'
WITHOUT_PAM='YES'
WITHOUT_PAM_SUPPORT='YES'
WITHOUT_PROFILE='YES'
WITHOUT_QUOTAS='YES'
WITHOUT_RCS='YES'
WITHOUT_SHAREDOCS='YES'
WITHOUT_SYSINSTALL='YES'
" > "${SRC_CONF_FILE}"


echo "Creating ${MAKE_CONF_FILE}"
echo "
NO_PROFILE='YES'
WITHOUT_MODULES = sound ntfs msdosfs usb nfs nfsclient nfs_common nfslock

.if !defined(CC) || \${CC} == \"cc\"
CC=clang
.endif
.if !defined(CXX) || \${CXX} == \"c++\"
CXX=clang++
.endif
.if !defined(CPP) || \${CPP} == \"cpp\"
CPP=clang-cpp
.endif

# Don't die on warnings
NO_WERROR=
WERROR=

# Don't forget this when using Jails!
NO_FSCHG=
" > "${MAKE_CONF_FILE}"


echo "Copying prefiles from ServeD…"
${CP_BIN} -R "${PREFILES}" /

