#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.

cd src/

jars=`for i in ../lib/*.jar; do echo -n "$i:"; done`
files=`for i in *.scala; do echo "$i"; done`

echo $jars
echo $files

out=`fsc -classpath $jars. $files`
ex="$?"
if [ "$ex" != "0" ]; then
  echo $out | most -w
fi

exit $ex