#!/bin/bash
# This Software is a close code project. You may not redistribute this code without permission of author.
cd src/

jars=`for i in ../lib/*.jar; do echo -n "$i:"; done`
packageDir="scalabot"
main="$packageDir.ScalaBot"
tests=`for i in *Test.scala; do echo -n "$i:"; done`

echo "Running tests.."
for i in $tests; do
	scala -classpath $jars. $packageDir.tests.${i%%.*}
done	

echo "Running $packageDir"
scala -classpath $jars. $main
