package skeletons

/**
 * User: dmilith
 * Date: Aug 28, 2009
 * Time: 1:08:06 AM
 */

class MacStartingScriptSkeleton {

val commonScriptStub = """
#!/bin/bash
# generated by Deployer by Daniel (dmilith) Dettlaff
declare script_dir script_path
# man bash 2>/dev/null | less -p 'BASH_SOURCE'
[[ ${BASH_VERSINFO[0]} -le 2 ]] && echo 'The BASH_SOURCE array variable is only available for Bash 3.0 and higher!' && exit 1
[[ "${BASH_SOURCE[0]}" != "${0}" ]] && echo "script ${BASH_SOURCE[0]} is running sourced ..."
script_path="$(cd $(/usr/bin/dirname "${BASH_SOURCE[0]}"); pwd -P)/$(/usr/bin/basename "${BASH_SOURCE[0]}")"
[[ ! -f "$script_path" ]] && script_path="$(cd $(/usr/bin/dirname "$0"); pwd -P)/$(/usr/bin/basename "$0")"
[[ ! -f "$script_path" ]] && script_path="" && echo 'No full path to running script found!' && exit 1
# full path to executing script's directory
script_dir="${script_path%/*}"
echo "script_dir: ${script_dir}"
APP_PACKAGE="$script_dir/../../"
"""


//
	//
	//  script MODEL:
	//
//
//
//MAIN="codadris.coviob2.App_Coviob2"
//
//java -Dfile.encoding=UTF-8 \
//-server \
//-XX:+UseBiasedLocking \
//-XX:+UseParallelGC \
//-Xmx1024m \
//-XX:MaxPermSize=512m \
//-XX:MaxHeapFreeRatio=15 \
//-XX:MinHeapFreeRatio=5 \
//-XX:+AggressiveOpts \
//-XX:CompileThreshold=1000 \
//-XX:+UseCompressedOops \
//-ea \
//-Dcom.apple.mrj.application.apple.menu.about.name=Coviob2 \
//-XX:+CITime \
//-classpath \
//$APP_PACKAGE/lib/org.quaqua-5.4.1.jar:\
//$APP_PACKAGE/lib/org.quaqua.swing-layout-5.4.1.jar:\
//$APP_PACKAGE/lib/junit-4.4.jar:\
//$APP_PACKAGE/lib/log4j-1.2.14.jar:\
//$APP_PACKAGE/lib/commons-io-1.4.jar:\
//$APP_PACKAGE/lib/commons-lang-2.4.jar:\
//$APP_PACKAGE/lib/commons-logging-1.1.1.jar:\
//$APP_PACKAGE/lib/looks-2.1.2.jar:\
//$APP_PACKAGE/lib/skinlf-1.2.3.jar:\
//$APP_PACKAGE/lib/scala-library-2.7.5.jar:\
//$APP_PACKAGE/lib/swingx-0.9.5-2.jar:\
//$APP_PACKAGE/lib/filters-2.0.235.jar:\
//$APP_PACKAGE/lib/swing-layout-1.0.jar:\
//$APP_PACKAGE/lib/jfreechart-1.0.9.jar:\
//$APP_PACKAGE/lib/jcommon-1.0.12.jar:\
//$APP_PACKAGE/lib/jargs-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/timingframework-1.0.jar:\
//$APP_PACKAGE/lib/flexdock_codadris-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/net.jcip.annotations-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.binblocklang-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui.screenspace-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui.suite-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui.textedit-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui.treetable-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui.utils-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.dbapp-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.dbgui-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.dbgui.scala-1.0-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/codadris.gui-0.0.1-SNAPSHOT.jar:\
//$APP_PACKAGE/lib/substance-5.1.jar:\
//$APP_PACKAGE/lib/beansbinding-1.2.1.jar:\
//$APP_PACKAGE/lib/codadris.utils-0.0.1-SNAPSHOT.jar \
//$MAIN


}